[tool.poetry]
name = "sprawozdanie"
version = "0.1.0"
description = ""
authors = ["ErykMMichalL"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
sphinx = "^6.1.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
